name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run pytest
        run: uv run pytest tests/

      - name: Run flake8
        run: uv run flake8 .

      - name: Run mypy
        run: uv run mypy .
